# Generated by Django 5.0.3 on 2024-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название упражнения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('exercise_type', models.CharField(choices=[('Cardio', 'Кардио-тренировка'), ('Power', 'Силовая тренировка'), ('Stretching', 'Растяжка'), ('Statics', 'Статические упражнения'), ('Average', 'Другое')], max_length=20, verbose_name='Тип упраженения')),
                ('difficulty_level', models.CharField(choices=[('Beginning', 'Начинающий'), ('Average', 'Средний'), ('Advanced', 'Продвинутый')], max_length=20, verbose_name='Уровень сложности')),
                ('duration', models.TimeField(verbose_name='Время на выполнение')),
                ('approaches', models.IntegerField(verbose_name='Количество подходов')),
                ('repetition', models.IntegerField(verbose_name='Количество повторений')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
    ]
